all:
	docker build -t mulatocloud/images .
	docker tag mulatocloud/images:latest 709142056059.dkr.ecr.us-east-1.amazonaws.com/mulatocloud/images:latest
	docker push 709142056059.dkr.ecr.us-east-1.amazonaws.com/mulatocloud/images:latest
