apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: haproxy
  namespace: ingress-haproxy
spec:
  chart:
    spec:
      chart: kubernetes-ingress
      sourceRef:
        kind: HelmRepository
        name: haproxytech
        namespace: flux-system
  interval: 10m
  values:
    controller:
      ingressClass: haproxy
      service:
        type: LoadBalancer
