---
apiVersion: v1
kind: Secret
metadata:
  name: batman-cluster-secret
  namespace: database
type: kubernetes.io/basic-auth
stringData:
  username: dedicated_admin
  password: "heyholetsgo"
---
apiVersion: v1
kind: Secret
metadata:
  name: robin-cluster-secret
  namespace: database
type: kubernetes.io/basic-auth
stringData:
  username: dedicated_admin
  password: "heyholetsgo"
